export interface SeedSpacingCropSource {
  label: string;
  url: string;
  role: 'primary' | 'secondary' | 'tertiary';
  fieldUsed: string;
}

export interface SeedSpacingCropFaq {
  q: string;
  a: string;
  sourceUrl: string;
}

export interface SeedSpacingCrop {
  slug: string;
  name: string;
  titleName: string;
  rowSpacingInches: number;
  plantSpacingInches: number;
  seedDepthInches: string;
  maturityDays: string;
  plantingMethod: string;
  maturitySpacingNote: string;
  raisedBedNote: string;
  intensiveNote: string;
  mistakeNote: string;
  airflowNote: string;
  harvestNote: string;
  primarySource: SeedSpacingCropSource;
  secondarySource: SeedSpacingCropSource;
  tertiarySource: SeedSpacingCropSource;
  uniqueFaq: SeedSpacingCropFaq;
}

export const seedSpacingCrops: SeedSpacingCrop[] = [
  {
    slug: 'tomato',
    name: 'Tomato',
    titleName: 'Tomato',
    rowSpacingInches: 36,
    plantSpacingInches: 24,
    seedDepthInches: '1/4 inch',
    maturityDays: '70-85 days',
    plantingMethod: 'Usually started indoors and transplanted after frost.',
    maturitySpacingNote: 'Tomatoes fill their lane quickly once staking, suckering, and fruit load increase canopy size, so the mature plant needs more airflow than a seedling suggests.',
    raisedBedNote: 'Raised beds can hold tomatoes slightly tighter than wide field rows, but caged or staked plants still need room for pruning, harvest, and leaf drying after irrigation.',
    intensiveNote: 'Intensive spacing only works when support, pruning, and watering are disciplined; otherwise foliage overlap pushes disease pressure up fast.',
    mistakeNote: 'The most common spacing mistake is treating a transplant like a compact patio tomato and then losing airflow once vines stretch and fruit clusters stack up.',
    airflowNote: 'Tomatoes are one of the clearest examples of why row spacing protects airflow, spray access, and blight management rather than just walking room.',
    harvestNote: 'Tighter rows make early planting feel efficient, but they complicate harvest and trellis access once plants hit full height.',
    primarySource: {
      label: 'University of Minnesota Extension',
      url: 'https://extension.umn.edu/vegetables/growing-tomatoes',
      role: 'primary',
      fieldUsed: 'row spacing and plant spacing',
    },
    secondarySource: {
      label: 'UGA Cooperative Extension planting chart',
      url: 'https://extension.uga.edu/content/dam/extension-county-offices/gwinnett-county/anr/homeshow-resources/Vegetable%20Planting%20Chart.pdf',
      role: 'secondary',
      fieldUsed: 'seed depth cross-check',
    },
    tertiarySource: {
      label: 'Penn State Extension — Tomato Production',
      url: 'https://extension.psu.edu/tomato-production',
      role: 'tertiary',
      fieldUsed: 'row spacing and plant spacing reference',
    },
    uniqueFaq: {
      q: 'How far apart should caged tomato plants be in a home garden?',
      a: 'Caged tomato plants usually still need about the same in-row spacing as staked plants because the cage does not reduce canopy width very much once the plant is loaded with leaves and fruit. The cage mainly changes support style, not the final need for airflow, harvest access, and disease prevention around the plant.',
      sourceUrl: 'https://extension.umn.edu/vegetables/growing-tomatoes',
    },
  },
  {
    slug: 'lettuce',
    name: 'Lettuce',
    titleName: 'Lettuce',
    rowSpacingInches: 12,
    plantSpacingInches: 8,
    seedDepthInches: '1/4 inch',
    maturityDays: '45-60 days',
    plantingMethod: 'Usually direct sown or transplanted in cool weather blocks.',
    maturitySpacingNote: 'Leaf lettuce tolerates tighter spacing than head lettuce, but mature heads still need enough room to dry after rain and avoid soft rot in crowded beds.',
    raisedBedNote: 'Lettuce is well suited to raised-bed planting because shallow roots and short height let you use close blocks without sacrificing too much access.',
    intensiveNote: 'Intensive beds work best when you are honest about harvest goal: baby leaf spacing is not the same as full head spacing.',
    mistakeNote: 'A common mistake is sowing for baby greens and then forgetting to thin when the goal shifts to full heads.',
    airflowNote: 'Even short crops like lettuce benefit from spacing that allows the canopy to dry quickly, especially in cool spring or fall weather.',
    harvestNote: 'The right spacing also affects harvest rhythm: tighter spacing may increase baby-leaf yield but reduces full-head size and uniformity.',
    primarySource: {
      label: 'Utah State University Extension',
      url: 'https://extension.usu.edu/vegetableguide/leafy-greens/planting-spacing',
      role: 'primary',
      fieldUsed: 'row spacing and plant spacing',
    },
    secondarySource: {
      label: 'UGA Cooperative Extension planting chart',
      url: 'https://extension.uga.edu/content/dam/extension-county-offices/gwinnett-county/anr/homeshow-resources/Vegetable%20Planting%20Chart.pdf',
      role: 'secondary',
      fieldUsed: 'seed depth and timing cross-check',
    },
    tertiarySource: {
      label: 'University of Maryland Extension — Growing Lettuce in a Home Garden',
      url: 'https://extension.umd.edu/resource/growing-lettuce-home-garden',
      role: 'tertiary',
      fieldUsed: 'head and leaf lettuce spacing reference',
    },
    uniqueFaq: {
      q: 'Should head lettuce be spaced wider than cut-and-come-again lettuce?',
      a: 'Yes. Head lettuce needs enough space to size up and close its canopy, while cut-and-come-again plantings are intentionally tighter because the harvest happens earlier and before each plant reaches full head size. The spacing decision should match the harvest style, not just the seed packet crop name.',
      sourceUrl: 'https://extension.usu.edu/vegetableguide/leafy-greens/planting-spacing',
    },
  },
  {
    slug: 'carrot',
    name: 'Carrot',
    titleName: 'Carrot',
    rowSpacingInches: 12,
    plantSpacingInches: 3,
    seedDepthInches: '1/4 to 1/2 inch',
    maturityDays: '60-80 days',
    plantingMethod: 'Direct sow only for straight roots and uniform stands.',
    maturitySpacingNote: 'Carrot spacing matters less for top growth than for root straightness, shoulder size, and the ability of each root to expand without forking under pressure.',
    raisedBedNote: 'Raised beds are excellent for carrots because loose soil and clean thinning make close in-row spacing easier to manage than in heavier field soils.',
    intensiveNote: 'Intensive planting can work for carrots, but only if germination is even and you thin on time instead of letting roots crowd underground.',
    mistakeNote: 'The classic carrot mistake is skipping thinning because the bed looks sparse at emergence, then ending up with many small or twisted roots later.',
    airflowNote: 'Carrots do not need the same dramatic canopy airflow as tomatoes, but rows still need enough room for weeding, thinning, and clean irrigation access.',
    harvestNote: 'Spacing decisions show up directly at harvest: wider in-row room usually means fewer but more uniform roots, while crowding means more small roots.',
    primarySource: {
      label: 'UGA Cooperative Extension planting chart',
      url: 'https://extension.uga.edu/content/dam/extension-county-offices/gwinnett-county/anr/homeshow-resources/Vegetable%20Planting%20Chart.pdf',
      role: 'primary',
      fieldUsed: 'row spacing, plant spacing, and seed depth',
    },
    secondarySource: {
      label: 'Utah State University Vegetable Guide',
      url: 'https://extension.usu.edu/vegetableguide/root-crops/beets-and-turnips',
      role: 'secondary',
      fieldUsed: 'root-crop spacing pattern cross-check',
    },
    tertiarySource: {
      label: 'University of Maryland Extension — Growing Carrots in a Home Garden',
      url: 'https://extension.umd.edu/resource/growing-carrots-home-garden',
      role: 'tertiary',
      fieldUsed: 'thinning and in-row spacing reference',
    },
    uniqueFaq: {
      q: 'Why do crowded carrots stay thin even when the tops look healthy?',
      a: 'Crowded carrots can maintain decent top growth while still competing underground for the exact space the root needs to widen and stay straight. That is why good-looking tops do not guarantee good root size. In carrots, spacing is fundamentally a root-shape issue as much as a canopy issue.',
      sourceUrl: 'https://extension.uga.edu/content/dam/extension-county-offices/gwinnett-county/anr/homeshow-resources/Vegetable%20Planting%20Chart.pdf',
    },
  },
  {
    slug: 'pepper',
    name: 'Pepper',
    titleName: 'Pepper',
    rowSpacingInches: 24,
    plantSpacingInches: 18,
    seedDepthInches: '1/4 inch',
    maturityDays: '70-90 days',
    plantingMethod: 'Usually transplanted after soils warm and frost risk passes.',
    maturitySpacingNote: 'Peppers stay smaller than tomatoes, but mature plants still bulk up once branching starts and fruit load increases, so the spacing target should reflect the adult canopy.',
    raisedBedNote: 'Raised beds can hold peppers efficiently because plant width is moderate, yet beds that are too tight still make staking and harvest awkward.',
    intensiveNote: 'Intensive spacing is possible in warm, dry sites with strong pruning and mulching discipline, but tight peppers can trap humidity in humid regions.',
    mistakeNote: 'One common error is assuming pepper plants stay seedling-sized and planting them on tomato-style support spacing that is too narrow for fruiting branches.',
    airflowNote: 'Pepper spacing is partly a fruit-quality question because crowded canopies shade fruit and slow drying after rain or overhead water.',
    harvestNote: 'Adequate spacing also gives harvest hands room to reach mature fruit without breaking branches or knocking off flowers.',
    primarySource: {
      label: 'University of Minnesota Extension',
      url: 'https://extension.umn.edu/vegetables/growing-peppers',
      role: 'primary',
      fieldUsed: 'row spacing and plant spacing',
    },
    secondarySource: {
      label: 'UGA Cooperative Extension planting chart',
      url: 'https://extension.uga.edu/content/dam/extension-county-offices/gwinnett-county/anr/homeshow-resources/Vegetable%20Planting%20Chart.pdf',
      role: 'secondary',
      fieldUsed: 'seed depth cross-check',
    },
    tertiarySource: {
      label: 'Penn State Extension — Pepper Production',
      url: 'https://extension.psu.edu/pepper-production',
      role: 'tertiary',
      fieldUsed: 'row spacing and plant spacing reference',
    },
    uniqueFaq: {
      q: 'Can bell peppers be planted closer together than tomatoes?',
      a: 'Usually yes, because bell peppers stay shorter and narrower than indeterminate tomatoes, but “closer” does not mean crowded. Peppers still need enough space for branching, fruit set, and air movement through the canopy, especially when plants are loaded with fruit in humid weather.',
      sourceUrl: 'https://extension.umn.edu/vegetables/growing-peppers',
    },
  },
  {
    slug: 'cucumber',
    name: 'Cucumber',
    titleName: 'Cucumber',
    rowSpacingInches: 36,
    plantSpacingInches: 12,
    seedDepthInches: '1 inch',
    maturityDays: '50-70 days',
    plantingMethod: 'Usually direct sown after soils warm, though transplants are possible.',
    maturitySpacingNote: 'Cucumber spacing changes fast once vines run. What looks roomy at seeding can become a closed canopy in a short stretch of warm weather.',
    raisedBedNote: 'Raised beds work well for cucumbers if the bed has a trellis or a clear plan for vine direction, otherwise plants spill into walkways and shade neighbors.',
    intensiveNote: 'Intensive spacing is much safer on trellised cucumbers than on sprawling ground-grown cucumbers because vertical training restores airflow and harvest access.',
    mistakeNote: 'A frequent mistake is using bush-crop assumptions on vining cucumber cultivars, then losing the bed edge to vine spread by midseason.',
    airflowNote: 'Cucumbers repay good spacing with cleaner foliage, easier scouting, and less mildew pressure than crowded, ground-hugging vines.',
    harvestNote: 'Harvest frequency also matters: a properly spaced cucumber row is easier to pick regularly, which keeps fruit tender and productive.',
    primarySource: {
      label: 'University of Minnesota Extension',
      url: 'https://extension.umn.edu/vegetables/growing-cucumbers',
      role: 'primary',
      fieldUsed: 'row spacing and plant spacing',
    },
    secondarySource: {
      label: 'UGA Cooperative Extension planting chart',
      url: 'https://extension.uga.edu/content/dam/extension-county-offices/gwinnett-county/anr/homeshow-resources/Vegetable%20Planting%20Chart.pdf',
      role: 'secondary',
      fieldUsed: 'seed depth cross-check',
    },
    tertiarySource: {
      label: 'Iowa State University Extension — Growing Cucumbers in the Home Garden',
      url: 'https://yardandgarden.extension.iastate.edu/how-to/growing-cucumbers-home-garden',
      role: 'tertiary',
      fieldUsed: 'hill and row spacing reference',
    },
    uniqueFaq: {
      q: 'Does trellising let cucumber plants stay on tighter spacing?',
      a: 'Yes, trellising often allows cucumbers to use tighter ground spacing because vine growth is redirected upward instead of sprawling across the bed. The key benefit is not just saving space; it is restoring airflow, keeping fruit cleaner, and making harvest easier inside the same square footage.',
      sourceUrl: 'https://extension.umn.edu/vegetables/growing-cucumbers',
    },
  },
  {
    slug: 'broccoli',
    name: 'Broccoli',
    titleName: 'Broccoli',
    rowSpacingInches: 24,
    plantSpacingInches: 18,
    seedDepthInches: '1/4 to 1/2 inch',
    maturityDays: '60-80 days',
    plantingMethod: 'Usually started in flats and transplanted as a cool-season crop.',
    maturitySpacingNote: 'Broccoli spacing is driven by the head you want to finish. Crowded plants may still make foliage but often reduce head size and uniformity.',
    raisedBedNote: 'Raised beds can hold broccoli efficiently, but the crop still wants room for a broad leaf canopy and clean side access when heads begin to size.',
    intensiveNote: 'Intensive planting is possible for small-heading harvest goals, but standard head production benefits from enough spacing to let the center head size fully.',
    mistakeNote: 'The most common spacing error is forgetting how broad cool-season brassica leaves become by maturity and planting them like compact salad greens.',
    airflowNote: 'Good spacing helps brassicas dry after irrigation and also leaves room to inspect the crop for caterpillars and center-head quality.',
    harvestNote: 'Broccoli harvest is easier when mature heads can be cut cleanly without leaf crowding from neighboring plants.',
    primarySource: {
      label: 'University of Minnesota Extension',
      url: 'https://extension.umn.edu/vegetables/growing-broccoli',
      role: 'primary',
      fieldUsed: 'row spacing and plant spacing',
    },
    secondarySource: {
      label: 'UGA Cooperative Extension planting chart',
      url: 'https://extension.uga.edu/content/dam/extension-county-offices/gwinnett-county/anr/homeshow-resources/Vegetable%20Planting%20Chart.pdf',
      role: 'secondary',
      fieldUsed: 'seed depth cross-check',
    },
    tertiarySource: {
      label: 'University of Maryland Extension — Growing Broccoli in a Home Garden',
      url: 'https://extension.umd.edu/resource/growing-broccoli-home-garden',
      role: 'tertiary',
      fieldUsed: 'row spacing and plant spacing reference',
    },
    uniqueFaq: {
      q: 'Will broccoli heads stay smaller if I plant broccoli too close together?',
      a: 'Usually yes. Broccoli can still produce a crop when crowded, but close spacing often shifts the plant toward smaller central heads because each plant has less room to build a large leaf engine before heading. The result is often more plants but less individual head size and less uniform harvest timing.',
      sourceUrl: 'https://extension.umn.edu/vegetables/growing-broccoli',
    },
  },
  {
    slug: 'bush-bean',
    name: 'Bush Bean',
    titleName: 'Bush Bean',
    rowSpacingInches: 18,
    plantSpacingInches: 6,
    seedDepthInches: '1 inch',
    maturityDays: '50-60 days',
    plantingMethod: 'Usually direct sown in warm soil.',
    maturitySpacingNote: 'Bush beans stay compact, but they still branch enough at maturity that the row should not become a solid, damp wall of foliage.',
    raisedBedNote: 'Bush beans fit raised beds well because they mature quickly and can be block planted without the trellis demands of pole beans.',
    intensiveNote: 'They tolerate closer spacing than many fruiting crops, but the stand still needs room for airflow and picking inside the row.',
    mistakeNote: 'A common error is planting bush beans like peas or carrots and then discovering that low branches and pods are hard to reach in a packed stand.',
    airflowNote: 'Spacing matters for pod cleanliness and disease prevention, especially during humid weather when foliage stays damp after watering.',
    harvestNote: 'Adequate spacing makes repeat picking faster, which improves tenderness and keeps the planting productive.',
    primarySource: {
      label: 'University of Minnesota Extension',
      url: 'https://extension.umn.edu/vegetables/growing-beans',
      role: 'primary',
      fieldUsed: 'row spacing and plant spacing',
    },
    secondarySource: {
      label: 'UGA Cooperative Extension planting chart',
      url: 'https://extension.uga.edu/content/dam/extension-county-offices/gwinnett-county/anr/homeshow-resources/Vegetable%20Planting%20Chart.pdf',
      role: 'secondary',
      fieldUsed: 'seed depth cross-check',
    },
    tertiarySource: {
      label: 'University of Maryland Extension — Growing Beans in a Home Garden',
      url: 'https://extension.umd.edu/resource/growing-beans-home-garden',
      role: 'tertiary',
      fieldUsed: 'bush snap bean row and plant spacing reference',
    },
    uniqueFaq: {
      q: 'Why do bush beans need less space than pole beans but still not zero room?',
      a: 'Bush beans stay shorter and do not need trellis lanes, so they can use less space than pole beans. But the plants still branch, set pods along the canopy edge, and need enough room for airflow and harvest access. “Compact” is not the same as “crowd-proof.”',
      sourceUrl: 'https://extension.umn.edu/vegetables/growing-beans',
    },
  },
  {
    slug: 'sweet-corn',
    name: 'Sweet Corn',
    titleName: 'Sweet Corn',
    rowSpacingInches: 30,
    plantSpacingInches: 10,
    seedDepthInches: '1 to 1 1/2 inches',
    maturityDays: '70-95 days',
    plantingMethod: 'Direct sow in blocks for better pollination.',
    maturitySpacingNote: 'Sweet corn spacing is tied to pollination as much as plant size. The mature crop needs enough room for stalk strength, yet blocks must stay close enough for effective pollen movement.',
    raisedBedNote: 'Small raised beds can struggle with sweet corn because the crop wants block planting instead of a single decorative row, which quickly consumes bed area.',
    intensiveNote: 'Corn responds poorly to narrow, decorative rows because pollination and light capture depend on a real block, not just minimal spacing.',
    mistakeNote: 'The biggest mistake is planting one or two short rows instead of a block, then blaming spacing when poor pollination is the actual issue.',
    airflowNote: 'Airflow matters less dramatically than with tomatoes, but row width still affects access, wind movement, and the ability to hill or weed the stand.',
    harvestNote: 'Well-spaced blocks are easier to scout for ear fill and harvest quickly at peak eating quality.',
    primarySource: {
      label: 'University of Minnesota Extension',
      url: 'https://extension.umn.edu/vegetables/growing-sweet-corn',
      role: 'primary',
      fieldUsed: 'row spacing and plant spacing',
    },
    secondarySource: {
      label: 'UGA Cooperative Extension planting chart',
      url: 'https://extension.uga.edu/content/dam/extension-county-offices/gwinnett-county/anr/homeshow-resources/Vegetable%20Planting%20Chart.pdf',
      role: 'secondary',
      fieldUsed: 'seed depth cross-check',
    },
    tertiarySource: {
      label: 'University of Maryland Extension — Growing Sweet Corn in a Home Garden',
      url: 'https://extension.umd.edu/resource/growing-sweet-corn-home-garden',
      role: 'tertiary',
      fieldUsed: 'row spacing and block planting reference',
    },
    uniqueFaq: {
      q: 'Why is block planting more important than one long row for sweet corn spacing?',
      a: 'Sweet corn depends on wind pollination, so a block of plants improves the chance that pollen falls across many silks instead of blowing past a single narrow row. You can hit the “right” in-row spacing and still get poor ear fill if the planting shape is wrong. Block layout is part of spacing strategy for corn, not a separate decision.',
      sourceUrl: 'https://extension.umn.edu/vegetables/growing-sweet-corn',
    },
  },
  {
    slug: 'spinach',
    name: 'Spinach',
    titleName: 'Spinach',
    rowSpacingInches: 12,
    plantSpacingInches: 6,
    seedDepthInches: '1/2 inch',
    maturityDays: '35-50 days',
    plantingMethod: 'Direct sown in cool weather for cut leaf or bunch harvests.',
    maturitySpacingNote: 'Spinach can be planted closely for baby leaves, but full bunch or mature leaf harvests still need enough room to keep leaves clean and upright.',
    raisedBedNote: 'Raised beds suit spinach very well because the crop is shallow rooted and quick, making close, repeated sowings practical.',
    intensiveNote: 'Spinach handles intensive planting better than large fruiting vegetables, but the target harvest size should still dictate final spacing.',
    mistakeNote: 'The common mistake is using baby-leaf density and then waiting for a mature bunch harvest, which creates a tangled, damp stand.',
    airflowNote: 'Even cool-season greens need leaf drying room to reduce mildew and leaf spotting in dense spring plantings.',
    harvestNote: 'Spacing also affects harvest cleanliness: a slightly more open stand keeps leaves easier to wash and bunch.',
    primarySource: {
      label: 'Utah State University Extension',
      url: 'https://extension.usu.edu/vegetableguide/leafy-greens/planting-spacing',
      role: 'primary',
      fieldUsed: 'row spacing and plant spacing',
    },
    secondarySource: {
      label: 'UGA Cooperative Extension planting chart',
      url: 'https://extension.uga.edu/content/dam/extension-county-offices/gwinnett-county/anr/homeshow-resources/Vegetable%20Planting%20Chart.pdf',
      role: 'secondary',
      fieldUsed: 'seed depth cross-check',
    },
    tertiarySource: {
      label: 'University of Maryland Extension — Growing Spinach in a Home Garden',
      url: 'https://extension.umd.edu/resource/growing-spinach-home-garden',
      role: 'tertiary',
      fieldUsed: 'row and plant spacing reference',
    },
    uniqueFaq: {
      q: 'Can spinach stay closer together if I only want baby leaves?',
      a: 'Yes. Spinach can be planted much more densely for repeated baby-leaf cuts because the crop is harvested before each plant reaches full mature spread. But if your goal is larger leaves or bunch harvests, the stand still needs to be thinned to protect airflow, leaf quality, and harvest ease.',
      sourceUrl: 'https://extension.usu.edu/vegetableguide/leafy-greens/planting-spacing',
    },
  },
  {
    slug: 'kale',
    name: 'Kale',
    titleName: 'Kale',
    rowSpacingInches: 18,
    plantSpacingInches: 12,
    seedDepthInches: '1/2 inch',
    maturityDays: '50-65 days',
    plantingMethod: 'Can be direct sown or transplanted as a cool-season crop.',
    maturitySpacingNote: 'Kale starts small but matures into a broad, harvestable plant, especially when leaves are picked over a long season rather than once.',
    raisedBedNote: 'Raised beds support kale well, but pick-again harvest systems still need enough room for side access and leaf stripping over time.',
    intensiveNote: 'Tighter kale spacing works for baby leaf or short-season spring crops, but long-season bunching kale needs more breathing room.',
    mistakeNote: 'Gardeners often crowd kale because the transplant looks tiny, then end up with overlapping outer leaves and less room to harvest cleanly.',
    airflowNote: 'Kale spacing is partly a pest and disease issue because tight leaves trap moisture and hide caterpillar damage.',
    harvestNote: 'If you plan multiple pickings, treat spacing as a season-long management decision, not just a transplant-day convenience.',
    primarySource: {
      label: 'Utah State University Extension',
      url: 'https://extension.usu.edu/vegetableguide/leafy-greens/planting-spacing',
      role: 'primary',
      fieldUsed: 'row spacing and plant spacing',
    },
    secondarySource: {
      label: 'UGA Cooperative Extension planting chart',
      url: 'https://extension.uga.edu/content/dam/extension-county-offices/gwinnett-county/anr/homeshow-resources/Vegetable%20Planting%20Chart.pdf',
      role: 'secondary',
      fieldUsed: 'seed depth cross-check',
    },
    tertiarySource: {
      label: 'University of Maryland Extension — Growing Leafy Greens in a Home Garden',
      url: 'https://extension.umd.edu/resource/growing-leafy-greens-home-garden',
      role: 'tertiary',
      fieldUsed: 'row and plant spacing reference',
    },
    uniqueFaq: {
      q: 'Why does kale need more space for repeated harvest than for baby-leaf production?',
      a: 'Baby-leaf kale is harvested before each plant expands much, so it can stay closer. Repeated harvest kale is expected to keep producing large outer leaves over time, which means the mature plant needs more room for canopy growth, airflow, and hand access during harvest.',
      sourceUrl: 'https://extension.usu.edu/vegetableguide/leafy-greens/planting-spacing',
    },
  },
  {
    slug: 'onion',
    name: 'Onion',
    titleName: 'Onion',
    rowSpacingInches: 12,
    plantSpacingInches: 4,
    seedDepthInches: '1/2 inch',
    maturityDays: '90-120 days',
    plantingMethod: 'Often grown from sets or transplants, though seed is possible.',
    maturitySpacingNote: 'Onion spacing is really bulb-spacing. Tops may not look huge, but bulbs need their own widening zone if you want size rather than a stand of small onions.',
    raisedBedNote: 'Raised beds are useful for onions because shallow cultivation and close observation make it easier to maintain uniform spacing and weed pressure.',
    intensiveNote: 'Closer spacing can be useful when your harvest goal is scallions or small bulbs, but full-size bulb production needs more discipline.',
    mistakeNote: 'A common mistake is planting all onions at scallion density and then expecting large storage bulbs at the end of the season.',
    airflowNote: 'Onions do not create a heavy canopy, but orderly spacing still improves weed control and reduces neck crowding as bulbs finish.',
    harvestNote: 'Uniform spacing produces more even bulb sizing, which makes curing and storage easier later.',
    primarySource: {
      label: 'University of Minnesota Extension',
      url: 'https://extension.umn.edu/vegetables/growing-onions',
      role: 'primary',
      fieldUsed: 'row spacing and plant spacing',
    },
    secondarySource: {
      label: 'UGA Cooperative Extension planting chart',
      url: 'https://extension.uga.edu/content/dam/extension-county-offices/gwinnett-county/anr/homeshow-resources/Vegetable%20Planting%20Chart.pdf',
      role: 'secondary',
      fieldUsed: 'seed depth cross-check',
    },
    tertiarySource: {
      label: 'University of Maryland Extension — Growing Onions in a Home Garden',
      url: 'https://extension.umd.edu/resource/growing-onions-home-garden',
      role: 'tertiary',
      fieldUsed: 'row and plant spacing reference',
    },
    uniqueFaq: {
      q: 'Should onions be spaced differently for scallions versus storage bulbs?',
      a: 'Yes. Scallions can be grown at much tighter spacing because harvest happens before bulb expansion. Storage onions need more room so each bulb can size evenly without crowding its neighbors. The harvest target should determine the final spacing, not just the crop name “onion.”',
      sourceUrl: 'https://extension.umn.edu/vegetables/growing-onions',
    },
  },
  {
    slug: 'radish',
    name: 'Radish',
    titleName: 'Radish',
    rowSpacingInches: 6,
    plantSpacingInches: 2,
    seedDepthInches: '1/2 inch',
    maturityDays: '22-35 days',
    plantingMethod: 'Direct sown for quick, short harvest windows.',
    maturitySpacingNote: 'Radishes mature quickly, but root swelling still depends on giving each plant enough underground room instead of only top room.',
    raisedBedNote: 'Raised beds are ideal for radishes because shallow, stone-free soil and easy thinning help roots stay round and smooth.',
    intensiveNote: 'Radishes tolerate very close spacing for small salad roots, but severe crowding still reduces size and uniformity fast.',
    mistakeNote: 'The classic mistake is assuming radishes are so fast that thinning does not matter. It does, especially if you want crisp, even roots instead of a patch of tiny ones.',
    airflowNote: 'Foliage crowding is less dramatic here than in large crops, but spacing still helps keep leaves clean and roots easy to pull.',
    harvestNote: 'Because the crop matures so quickly, spacing errors show up almost immediately in root size and harvest uniformity.',
    primarySource: {
      label: 'University of Minnesota Extension',
      url: 'https://extension.umn.edu/vegetables/growing-radishes',
      role: 'primary',
      fieldUsed: 'row spacing and plant spacing',
    },
    secondarySource: {
      label: 'UGA Cooperative Extension planting chart',
      url: 'https://extension.uga.edu/content/dam/extension-county-offices/gwinnett-county/anr/homeshow-resources/Vegetable%20Planting%20Chart.pdf',
      role: 'secondary',
      fieldUsed: 'seed depth cross-check',
    },
    tertiarySource: {
      label: 'University of Maryland Extension — Growing Radishes in a Home Garden',
      url: 'https://extension.umd.edu/resource/growing-radishes-home-garden',
      role: 'tertiary',
      fieldUsed: 'in-row spacing and seed depth reference',
    },
    uniqueFaq: {
      q: 'Why do radishes crack or stay tiny when I skip thinning?',
      a: 'When radishes are not thinned, each root has less room to expand and the stand competes harder for moisture. That competition can leave roots undersized, irregular, or prone to splitting once water swings sharply. For a crop this fast, thinning is one of the highest-return spacing jobs you can do.',
      sourceUrl: 'https://extension.umn.edu/vegetables/growing-radishes',
    },
  },
  {
    slug: 'beet',
    name: 'Beet',
    titleName: 'Beet',
    rowSpacingInches: 12,
    plantSpacingInches: 4,
    seedDepthInches: '1/2 inch',
    maturityDays: '50-70 days',
    plantingMethod: 'Usually direct sown and then thinned after emergence.',
    maturitySpacingNote: 'Beet spacing works like other root crops: leaves may tolerate a little crowding, but roots need room to size evenly and stay marketable.',
    raisedBedNote: 'Raised beds suit beets because fine soil structure and easy thinning support smooth, evenly sized roots.',
    intensiveNote: 'Beets can be grown more densely for baby beet harvests, but standard roots still need enough space to widen without deforming each other.',
    mistakeNote: 'The biggest mistake is treating multigerm beet seed clusters like single seedlings and failing to thin after they emerge.',
    airflowNote: 'Leaf canopies are not huge, but spacing still protects access for weeding and keeps the root zone from becoming a tangled patch of undersized roots.',
    harvestNote: 'Uniform spacing is one of the easiest ways to get a more even harvest size instead of a mixed tray of very small and very large roots.',
    primarySource: {
      label: 'Utah State University Extension',
      url: 'https://extension.usu.edu/vegetableguide/root-crops/beets-and-turnips',
      role: 'primary',
      fieldUsed: 'row spacing and plant spacing',
    },
    secondarySource: {
      label: 'UGA Cooperative Extension planting chart',
      url: 'https://extension.uga.edu/content/dam/extension-county-offices/gwinnett-county/anr/homeshow-resources/Vegetable%20Planting%20Chart.pdf',
      role: 'secondary',
      fieldUsed: 'seed depth cross-check',
    },
    tertiarySource: {
      label: 'University of Maryland Extension — Growing Beets in a Home Garden',
      url: 'https://extension.umd.edu/resource/growing-beets-home-garden',
      role: 'tertiary',
      fieldUsed: 'in-row spacing and seed depth reference',
    },
    uniqueFaq: {
      q: 'Do beet seedlings need thinning even when the bed already looks sparse?',
      a: 'Usually yes, because one beet seedball can produce more than one seedling. A stand that looks light from above may still have too many plants sharing the same point underground. Thinning is often what separates a patch of beet greens from a patch of well-sized beet roots.',
      sourceUrl: 'https://extension.usu.edu/vegetableguide/root-crops/beets-and-turnips',
    },
  },
  {
    slug: 'zucchini',
    name: 'Zucchini',
    titleName: 'Zucchini',
    rowSpacingInches: 48,
    plantSpacingInches: 36,
    seedDepthInches: '1 inch',
    maturityDays: '45-60 days',
    plantingMethod: 'Usually direct sown after frost or transplanted carefully.',
    maturitySpacingNote: 'Zucchini becomes much wider than it looks at transplant stage, and mature leaves quickly dominate neighboring crops if the spacing is too optimistic.',
    raisedBedNote: 'Raised beds can grow zucchini well, but one plant can own a surprising amount of square footage, so spacing decisions matter more than many gardeners expect.',
    intensiveNote: 'Intensive spacing is risky unless you intentionally train or prune around the bed edge, because mature leaves will otherwise shade and crowd nearby crops.',
    mistakeNote: 'A classic mistake is treating zucchini like cucumber spacing even though the plant often forms a larger mound and broader leaf canopy.',
    airflowNote: 'Good spacing keeps the plant open enough to spot powdery mildew, pollination issues, and hidden fruit before quality slips.',
    harvestNote: 'Zucchini is most productive when fruit is picked regularly, and adequate spacing makes that daily or near-daily harvest much easier.',
    primarySource: {
      label: 'UGA Cooperative Extension planting chart',
      url: 'https://extension.uga.edu/content/dam/extension-county-offices/gwinnett-county/anr/homeshow-resources/Vegetable%20Planting%20Chart.pdf',
      role: 'primary',
      fieldUsed: 'row spacing, plant spacing, and seed depth',
    },
    secondarySource: {
      label: 'University of Minnesota Extension',
      url: 'https://extension.umn.edu/vegetables/growing-squash',
      role: 'secondary',
      fieldUsed: 'maturity habit cross-check',
    },
    tertiarySource: {
      label: 'University of Maryland Extension — Growing Summer Squash (Zucchini) in a Home Garden',
      url: 'https://extension.umd.edu/resource/growing-summer-squash-zucchini-home-garden',
      role: 'tertiary',
      fieldUsed: 'hill and row spacing reference',
    },
    uniqueFaq: {
      q: 'Why does one zucchini plant seem to take over an entire corner of the bed?',
      a: 'Zucchini builds a large, broadleaf canopy very quickly once warm weather arrives, so the mature plant occupies far more room than the seedling or transplant suggests. That is why spacing has to be set for the adult mound and harvest access, not just for the young plant you put in the ground.',
      sourceUrl: 'https://extension.uga.edu/content/dam/extension-county-offices/gwinnett-county/anr/homeshow-resources/Vegetable%20Planting%20Chart.pdf',
    },
  },
  {
    slug: 'potato',
    name: 'Potato',
    titleName: 'Potato',
    rowSpacingInches: 30,
    plantSpacingInches: 12,
    seedDepthInches: '3 to 4 inches',
    maturityDays: '80-120 days',
    plantingMethod: 'Planted from seed pieces rather than true seed in most home gardens.',
    maturitySpacingNote: 'Potato spacing is tied to tuber set, hilling, and the need to keep developing potatoes covered as the season advances.',
    raisedBedNote: 'Raised beds can support potatoes well if the bed is deep enough for hilling and harvest, but the spacing still needs to leave room for canopy expansion and soil movement.',
    intensiveNote: 'Intensive spacing may increase plant count, but it can also reduce tuber sizing and complicate hilling if you do not leave enough row room.',
    mistakeNote: 'One common mistake is thinking only about the seed piece distance and forgetting that the row also needs space for hilling and later digging.',
    airflowNote: 'Good spacing improves canopy drying and gives you room to scout for foliar disease before the tops collapse.',
    harvestNote: 'Potato spacing also changes harvest labor: cramped rows are harder to hill, harder to dig, and easier to damage at harvest.',
    primarySource: {
      label: 'University of Minnesota Extension',
      url: 'https://extension.umn.edu/vegetables/growing-potatoes',
      role: 'primary',
      fieldUsed: 'row spacing and plant spacing',
    },
    secondarySource: {
      label: 'UGA Cooperative Extension planting chart',
      url: 'https://extension.uga.edu/content/dam/extension-county-offices/gwinnett-county/anr/homeshow-resources/Vegetable%20Planting%20Chart.pdf',
      role: 'secondary',
      fieldUsed: 'planting depth cross-check',
    },
    tertiarySource: {
      label: 'Iowa State University Extension — Planting Potatoes in the Home Garden',
      url: 'https://yardandgarden.extension.iastate.edu/article/2020/03/planting-potatoes-home-garden',
      role: 'tertiary',
      fieldUsed: 'row spacing, plant spacing, and seed depth reference',
    },
    uniqueFaq: {
      q: 'Why does potato spacing have to leave room for hilling as well as plant growth?',
      a: 'Potatoes are not managed like surface-rooted greens. The crop needs row room for hilling soil around stems as tubers develop and for digging later without cutting too many potatoes. A row that looks efficient on planting day can become a management problem if it leaves no working room for hilling or harvest.',
      sourceUrl: 'https://extension.umn.edu/vegetables/growing-potatoes',
    },
  },
  {
    slug: 'garlic',
    name: 'Garlic',
    titleName: 'Garlic',
    rowSpacingInches: 12,
    plantSpacingInches: 6,
    seedDepthInches: '2 inches',
    maturityDays: '240+ days (fall planting to summer harvest)',
    plantingMethod: 'Planted from cloves in autumn for harvest the following summer.',
    maturitySpacingNote: 'Garlic spacing is bulb spacing. Tops stay slim, but the bulb still needs underground room to widen instead of staying small and tightly clustered.',
    raisedBedNote: 'Raised beds suit garlic well because loose, well-drained soil supports clean bulb expansion and easier harvest with a fork.',
    intensiveNote: 'Closer spacing can be used for green garlic harvest, but storage bulb production needs the standard in-row distance to avoid undersized heads.',
    mistakeNote: 'A common mistake is planting garlic at scallion density and then expecting full-size storage bulbs at the end of the long season.',
    airflowNote: 'Garlic is not a heavy canopy crop, but enough spacing keeps weed pressure manageable and lets bulbs cure cleanly as foliage dries down.',
    harvestNote: 'Spacing decisions show up at harvest as bulb size: crowded plantings often leave a stand of small heads instead of a few well-formed ones.',
    primarySource: {
      label: 'University of Minnesota Extension — Growing Garlic',
      url: 'https://extension.umn.edu/vegetables/growing-garlic',
      role: 'primary',
      fieldUsed: 'row spacing and plant spacing',
    },
    secondarySource: {
      label: 'UGA Cooperative Extension planting chart',
      url: 'https://extension.uga.edu/content/dam/extension-county-offices/gwinnett-county/anr/homeshow-resources/Vegetable%20Planting%20Chart.pdf',
      role: 'secondary',
      fieldUsed: 'planting depth cross-check',
    },
    tertiarySource: {
      label: 'University of Maryland Extension — Growing Garlic in a Home Garden',
      url: 'https://extension.umd.edu/resource/growing-garlic-home-garden',
      role: 'tertiary',
      fieldUsed: 'row spacing, plant spacing, and clove depth reference',
    },
    uniqueFaq: {
      q: 'Why is fall planting timing as important as spacing for garlic bulb size?',
      a: 'Garlic needs enough cool weeks before winter to set roots, then a cold period to trigger bulb formation in spring. Even with perfect spacing, late planting can give you small bulbs because the plant did not get enough early root development. Spacing protects mature bulb size; timing protects whether the plant ever reaches mature bulb stage at all.',
      sourceUrl: 'https://extension.umn.edu/vegetables/growing-garlic',
    },
  },
  {
    slug: 'pea',
    name: 'Pea',
    titleName: 'Pea',
    rowSpacingInches: 24,
    plantSpacingInches: 2,
    seedDepthInches: '1 to 1 1/2 inches',
    maturityDays: '60-70 days',
    plantingMethod: 'Direct sown in cool spring or fall soil; benefits from a trellis for tall varieties.',
    maturitySpacingNote: 'Peas tolerate close in-row spacing because vines climb instead of spreading sideways, but rows still need real width for trellis access and pod harvest.',
    raisedBedNote: 'Raised beds work well for peas if a trellis or netting is built into the bed plan; without vertical support, vines collapse and crowding becomes worse.',
    intensiveNote: 'Tight in-row planting is normal for peas, but row width should not be cut to match it — narrow rows make trellising and picking impossible later.',
    mistakeNote: 'A frequent mistake is treating peas like beans and planting wide in-row spacing, which leaves too few plants per foot to hold the trellis or fill the row.',
    airflowNote: 'Peas need airflow on the leaf canopy because cool, wet weather encourages powdery mildew once vines stack against each other.',
    harvestNote: 'Spacing also affects how long the harvest window lasts: an organized trellised row holds more pickable pods than a tangled, collapsed planting.',
    primarySource: {
      label: 'University of Minnesota Extension — Growing Peas',
      url: 'https://extension.umn.edu/vegetables/growing-peas',
      role: 'primary',
      fieldUsed: 'row spacing and plant spacing',
    },
    secondarySource: {
      label: 'UGA Cooperative Extension planting chart',
      url: 'https://extension.uga.edu/content/dam/extension-county-offices/gwinnett-county/anr/homeshow-resources/Vegetable%20Planting%20Chart.pdf',
      role: 'secondary',
      fieldUsed: 'seed depth cross-check',
    },
    tertiarySource: {
      label: 'University of Maryland Extension — Growing Peas in a Home Garden',
      url: 'https://extension.umd.edu/resource/growing-peas-home-garden',
      role: 'tertiary',
      fieldUsed: 'row spacing and trellis layout reference',
    },
    uniqueFaq: {
      q: 'Why do peas need close in-row spacing but still need wide row spacing?',
      a: 'Pea vines climb a trellis rather than spreading sideways, so plants can stand close to each other without shading neighbors. But the row still needs width because each side of the trellis has to be reachable for picking, and the trellis itself takes up real ground space. Close in-row spacing fills the trellis; wide row spacing keeps the row workable.',
      sourceUrl: 'https://extension.umn.edu/vegetables/growing-peas',
    },
  },
  {
    slug: 'cabbage',
    name: 'Cabbage',
    titleName: 'Cabbage',
    rowSpacingInches: 24,
    plantSpacingInches: 18,
    seedDepthInches: '1/4 to 1/2 inch',
    maturityDays: '70-100 days',
    plantingMethod: 'Usually started in flats and transplanted as a cool-season crop.',
    maturitySpacingNote: 'Cabbage spacing controls head size more than plant survival. Crowded plants may still grow leaves but often head up small or unevenly.',
    raisedBedNote: 'Raised beds suit cabbage if soil is deep and even, but the broad mature canopy still needs room or it will shade neighbors and stay damp after rain.',
    intensiveNote: 'Tighter spacing works for small early-cabbage varieties, but full-size storage cabbage benefits from the standard in-row distance for clean head formation.',
    mistakeNote: 'A common mistake is treating a small transplant like a salad-green seedling and then watching the mature crop overrun the bed by midseason.',
    airflowNote: 'Spacing protects airflow under broad outer leaves, which reduces slug habitat and slows the spread of cabbage diseases in damp weather.',
    harvestNote: 'Adequate spacing also makes harvest cleaner because the head can be cut without crushing or bruising leaves on neighboring plants.',
    primarySource: {
      label: 'University of Minnesota Extension — Growing Cabbage',
      url: 'https://extension.umn.edu/vegetables/growing-cabbage',
      role: 'primary',
      fieldUsed: 'row spacing and plant spacing',
    },
    secondarySource: {
      label: 'UGA Cooperative Extension planting chart',
      url: 'https://extension.uga.edu/content/dam/extension-county-offices/gwinnett-county/anr/homeshow-resources/Vegetable%20Planting%20Chart.pdf',
      role: 'secondary',
      fieldUsed: 'seed depth cross-check',
    },
    tertiarySource: {
      label: 'University of Maryland Extension — Growing Cabbage in a Home Garden',
      url: 'https://extension.umd.edu/resource/growing-cabbage-home-garden',
      role: 'tertiary',
      fieldUsed: 'row spacing and plant spacing reference',
    },
    uniqueFaq: {
      q: 'Does tighter cabbage spacing produce more total harvest or just smaller heads?',
      a: 'Usually it produces smaller, less uniform heads rather than more total weight. Cabbage has a fairly fixed head-size potential per plant, and crowding compresses that potential. You can grow more plants per square foot, but the per-head harvest typically drops faster than the plant count rises, so total useful weight rarely increases the way the math suggests.',
      sourceUrl: 'https://extension.umn.edu/vegetables/growing-cabbage',
    },
  },
  {
    slug: 'cauliflower',
    name: 'Cauliflower',
    titleName: 'Cauliflower',
    rowSpacingInches: 30,
    plantSpacingInches: 18,
    seedDepthInches: '1/4 to 1/2 inch',
    maturityDays: '75-100 days',
    plantingMethod: 'Usually started in flats and transplanted as a cool-season crop with steady moisture.',
    maturitySpacingNote: 'Cauliflower spacing matters more than the seedling suggests because head quality depends on uninterrupted growth. Crowded plants stress easily and often produce small or loose heads.',
    raisedBedNote: 'Raised beds work for cauliflower only if soil is deep, evenly moist, and roomy enough for the broad outer leaves to expand without overlap.',
    intensiveNote: 'Tighter spacing is risky because cauliflower is more sensitive to growth checks than cabbage; any stress from crowding can ruin head formation.',
    mistakeNote: 'A frequent mistake is using cabbage spacing for cauliflower; cauliflower really does prefer a slightly wider row to support steady, uninterrupted leaf growth.',
    airflowNote: 'Wide spacing helps the long maturity window stay manageable, especially since the developing curd benefits from leaf cover that does not collapse from crowding.',
    harvestNote: 'A roomy stand also makes the visual check for harvest readiness easier because curds need to be inspected through outer leaves without disturbing neighbors.',
    primarySource: {
      label: 'University of Minnesota Extension — Growing Cauliflower',
      url: 'https://extension.umn.edu/vegetables/growing-cauliflower',
      role: 'primary',
      fieldUsed: 'row spacing and plant spacing',
    },
    secondarySource: {
      label: 'UGA Cooperative Extension planting chart',
      url: 'https://extension.uga.edu/content/dam/extension-county-offices/gwinnett-county/anr/homeshow-resources/Vegetable%20Planting%20Chart.pdf',
      role: 'secondary',
      fieldUsed: 'seed depth cross-check',
    },
    tertiarySource: {
      label: 'University of Maryland Extension — Growing Cauliflower in a Home Garden',
      url: 'https://extension.umd.edu/resource/growing-cauliflower-home-garden',
      role: 'tertiary',
      fieldUsed: 'row spacing and plant spacing reference',
    },
    uniqueFaq: {
      q: 'Why does cauliflower need slightly wider spacing than broccoli or cabbage?',
      a: 'Cauliflower is more sensitive to growth interruptions than its brassica neighbors. Any stress — crowding, irregular water, heat spikes — can produce small or grainy heads. Wider spacing acts as a buffer against those stresses by giving each plant room to grow steadily without competing for light, water, or root space at critical curd-formation stages.',
      sourceUrl: 'https://extension.umn.edu/vegetables/growing-cauliflower',
    },
  },
  {
    slug: 'swiss-chard',
    name: 'Swiss Chard',
    titleName: 'Swiss Chard',
    rowSpacingInches: 18,
    plantSpacingInches: 12,
    seedDepthInches: '1/2 inch',
    maturityDays: '50-60 days',
    plantingMethod: 'Direct sown or transplanted; tolerates both cool and warm weather.',
    maturitySpacingNote: 'Swiss chard spacing depends on harvest style. Cut-and-come-again rows can stay tighter, but full-size mature plants need room to keep producing large outer leaves over a long season.',
    raisedBedNote: 'Raised beds suit chard well because the crop is shallow rooted and tolerates repeat picking; bed access stays manageable as long as plants are not crammed shoulder to shoulder.',
    intensiveNote: 'Closer spacing works for baby leaf production, but if you plan to harvest chard for months, the standard plant spacing supports steadier yield without midseason crowding.',
    mistakeNote: 'A common mistake is sowing chard at lettuce density and then expecting the same plants to keep producing through summer; the stand quickly becomes too dense for repeated picking.',
    airflowNote: 'Chard handles humid weather better than many greens, but tight stands still trap leaf moisture and can encourage leaf-spot diseases in long, repeat-harvest plantings.',
    harvestNote: 'Spacing decisions show up most clearly in cut-and-come-again rhythm: well-spaced plants regrow cleanly while crowded ones produce smaller, slower outer leaves with each cut.',
    primarySource: {
      label: 'Utah State University Extension — Leafy Greens Planting Spacing',
      url: 'https://extension.usu.edu/vegetableguide/leafy-greens/planting-spacing',
      role: 'primary',
      fieldUsed: 'row spacing and plant spacing',
    },
    secondarySource: {
      label: 'UGA Cooperative Extension planting chart',
      url: 'https://extension.uga.edu/content/dam/extension-county-offices/gwinnett-county/anr/homeshow-resources/Vegetable%20Planting%20Chart.pdf',
      role: 'secondary',
      fieldUsed: 'seed depth cross-check',
    },
    tertiarySource: {
      label: 'University of Maryland Extension — Growing Leafy Greens in a Home Garden',
      url: 'https://extension.umd.edu/resource/growing-leafy-greens-home-garden',
      role: 'tertiary',
      fieldUsed: 'row and plant spacing reference',
    },
    uniqueFaq: {
      q: 'Why does Swiss chard spacing matter for cut-and-come-again harvests?',
      a: 'Chard is a long-season repeat-harvest crop, not a one-cut salad green. Each plant keeps pushing new outer leaves from the crown for months, and crowded crowns produce smaller, weaker leaves with every cycle. Adequate spacing is what lets the plant keep replacing harvested leaves at full size instead of gradually shrinking the harvest as the season progresses.',
      sourceUrl: 'https://extension.usu.edu/vegetableguide/leafy-greens/planting-spacing',
    },
  },
]

export const seedSpacingCropMap = Object.fromEntries(seedSpacingCrops.map((crop) => [crop.slug, crop])) as Record<string, SeedSpacingCrop>

const seedDepthForTable = (depth: string) =>
  depth
    .replace(/ inches?/g, ' in')
    .replace(/inch/g, 'in')

export const seedSpacingCropTableRows: string[][] = seedSpacingCrops.map((crop) => [
  crop.name,
  `${crop.rowSpacingInches} × ${crop.plantSpacingInches} in`,
  seedDepthForTable(crop.seedDepthInches),
])

const popularSeedSpacingSlugs = ['tomato', 'pepper', 'cucumber', 'lettuce', 'carrot']

export const popularSeedSpacingCropTableRows: string[][] = popularSeedSpacingSlugs.map((slug) => {
  const crop = seedSpacingCropMap[slug]
  return [
    crop.name,
    `${crop.rowSpacingInches} × ${crop.plantSpacingInches} in`,
    seedDepthForTable(crop.seedDepthInches),
  ]
})

export const seedSpacingCropLinks = seedSpacingCrops.map((crop) => ({
  href: `/tools/seed-spacing/${crop.slug}`,
  anchor: `${crop.titleName} spacing guide`,
  description: `See ${crop.titleName.toLowerCase()} row spacing, plant spacing, seed depth, maturity notes, and crop-specific FAQs.`,
}))
